function [ arrayMutInfo, arrayPearsCorr ] = calcStatAssoc( structInputData )
%% [ arrayMutInfo, arrayPearsCorr ] = calcStatAssoc( structInputData )
% TODO: Write structSettings.loadStatAssoc into the function & script
% This function is designed to take in a structured array which specifies
%  the miR and mRNA data, and calculates the mutual information and
%  Pearson's correlation between all pairwise combinations of miR vs mRNA
%
%  Inputs:
%   - structInputData: a structured array which contains the miR and mRNA
%           data; generated by loadLudwigData
%
%  Output:
%   - arrayMutInfo: a 2D (n_miRs*n_mRNAs) double array containing the
%       mutual information between all miR-vs-mRNA pairs
%   - arrayPearsCorr: a 2D (n_miRs*n_mRNAs) double array containing the
%       Pearson's correlation between all miR-vs-mRNA pairs
%               
%  MATLAB Toolbox Dependencies:
%   - Statistics and Machine Learning Toolbox (for calc in 
%       informationDynamics)
%
%  Function dependencies
%   - informationDynamics: calculates measures of pairwise statistical
%       association
%
% This script uses the information dynamics function which was written by
% David Budden
% 
% This function was created by Joe Cursons:
%   joseph.cursons@unimelb.edu.au
%
% Last Updated: 03/03/16
%
 %  %  %  %  %  %  %  %  %  %  %  %  %  %  %  %  %  %  %  %  %  %  %  %  %  
%% Perform pre-processing
 %  %  %  %  %  %  %  %  %  %  %  %  %  %  %  %  %  %  %  %  %  %  %  %  %  

    %extract the string lengths for the mRNA data cell lines, for
    % subsequent indexing
    arrayMessRNACellLineStrLength = zeros(length(structInputData(2).CellLine),1,'uint8');
    for iCellLine = 1:length(structInputData(2).CellLine),
        arrayMessRNACellLineStrLength(iCellLine) = length(structInputData(2).CellLine{iCellLine});
    end

    %extract the number of miRs and mRNAs for creating the output arrays
    numMicroRNAs = length(structInputData(1).Target);
    numMessRNAs = length(structInputData(2).Target);

 %  %  %  %  %  %  %  %  %  %  %  %  %  %  %  %  %  %  %  %  %  %  %  %  %  
%% Create and populate the output arrays
 %  %  %  %  %  %  %  %  %  %  %  %  %  %  %  %  %  %  %  %  %  %  %  %  %  

    %create the output arrays
    arrayMutInfo = zeros(numMicroRNAs,numMessRNAs,'double');
    arrayPearsCorr = zeros(numMicroRNAs,numMessRNAs,'double');
    %move through all pairwise combinations of miRs
    for iMicRNA = 1:numMicroRNAs,
        
        %output progress for the analysis
        disp(['iMicRNA = ' num2str(iMicRNA) '/' num2str(numMicroRNAs)]);
        
        %read the vector directly from the micro-RNA data; transpose for the
        %information dynamics funciton
        arrayMicRNAData = structInputData(1).Data(iMicRNA,:)';
        
    %and mRNAs
        for iMesRNA = 1:numMessRNAs,

            %extract the mRNA data and make sure that the cell lines are
            %properly matched
            arrayMessRNAData = zeros(length(structInputData(1).CellLine),1,'double');
            
            %match the miR and mRNA data by cell line
            for iCellLine = 1:length(structInputData(1).CellLine),
                
                %extract the miR data cell line
                stringMicRNACellLine = structInputData(1).CellLine{iCellLine};

                %identify the index for this cell line in the mRNA data
                numCellLineForMessRNA = find( strncmp(stringMicRNACellLine,structInputData(2).CellLine,length(stringMicRNACellLine)) && ...
                                              (arrayMessRNACellLineStrLength == length(stringMicRNACellLine)) );
                if ~isempty(numCellLineForMessRNA),
                    %output
                    arrayMessRNAData(iCellLine) = structInputData(2).Data(iMesRNA,numCellLineForMessRNA);
                else
                    disp('Unable to find properly matching cell lines');
                end

            end

            %calculate statistical associations
            arrayMutInfo(iMicRNA,iMesRNA) = informationDynamics(arrayMicRNAData,arrayMessRNAData,'MutualInfoCalculatorMultiVariateKraskov2');
            arrayPearsCorr(iMicRNA,iMesRNA) = informationDynamics(arrayMicRNAData,arrayMessRNAData,'PearsCorr');

        end

    end
    

end

